name: Add Rules to Cloudflare Gateway
on:
  push:
  schedule:
    - cron: "0 1/1 * * *"
  workflow_dispatch:
jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Keep alive
        uses: gautamkrishnar/keepalive-workflow@v1

      - name: Cloudflare Gateway Zero Trust
        run: bash run.sh

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
